/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TanstackSudokuSudokuRouteRouteImport } from './routes/tanstack-sudoku/sudoku/route'
import { Route as TanstackSudokuSudokuIndexRouteImport } from './routes/tanstack-sudoku/sudoku/index'
import { Route as TanstackSudokuSudokuRandomIndexRouteImport } from './routes/tanstack-sudoku/sudoku/random/index'
import { Route as TanstackSudokuSudokuSudokuIdIndexRouteImport } from './routes/tanstack-sudoku/sudoku/$sudokuId/index'
import { Route as TanstackSudokuSudokuRandomDifficultyRouteImport } from './routes/tanstack-sudoku/sudoku/random/$difficulty'
import { Route as TanstackSudokuSudokuSudokuIdSudokuProgressRouteImport } from './routes/tanstack-sudoku/sudoku/$sudokuId/$sudokuProgress'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TanstackSudokuSudokuRouteRoute =
  TanstackSudokuSudokuRouteRouteImport.update({
    id: '/tanstack-sudoku/sudoku',
    path: '/tanstack-sudoku/sudoku',
    getParentRoute: () => rootRouteImport,
  } as any)
const TanstackSudokuSudokuIndexRoute =
  TanstackSudokuSudokuIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TanstackSudokuSudokuRouteRoute,
  } as any)
const TanstackSudokuSudokuRandomIndexRoute =
  TanstackSudokuSudokuRandomIndexRouteImport.update({
    id: '/random/',
    path: '/random/',
    getParentRoute: () => TanstackSudokuSudokuRouteRoute,
  } as any)
const TanstackSudokuSudokuSudokuIdIndexRoute =
  TanstackSudokuSudokuSudokuIdIndexRouteImport.update({
    id: '/$sudokuId/',
    path: '/$sudokuId/',
    getParentRoute: () => TanstackSudokuSudokuRouteRoute,
  } as any)
const TanstackSudokuSudokuRandomDifficultyRoute =
  TanstackSudokuSudokuRandomDifficultyRouteImport.update({
    id: '/random/$difficulty',
    path: '/random/$difficulty',
    getParentRoute: () => TanstackSudokuSudokuRouteRoute,
  } as any)
const TanstackSudokuSudokuSudokuIdSudokuProgressRoute =
  TanstackSudokuSudokuSudokuIdSudokuProgressRouteImport.update({
    id: '/$sudokuId/$sudokuProgress',
    path: '/$sudokuId/$sudokuProgress',
    getParentRoute: () => TanstackSudokuSudokuRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tanstack-sudoku/sudoku': typeof TanstackSudokuSudokuRouteRouteWithChildren
  '/tanstack-sudoku/sudoku/': typeof TanstackSudokuSudokuIndexRoute
  '/tanstack-sudoku/sudoku/$sudokuId/$sudokuProgress': typeof TanstackSudokuSudokuSudokuIdSudokuProgressRoute
  '/tanstack-sudoku/sudoku/random/$difficulty': typeof TanstackSudokuSudokuRandomDifficultyRoute
  '/tanstack-sudoku/sudoku/$sudokuId': typeof TanstackSudokuSudokuSudokuIdIndexRoute
  '/tanstack-sudoku/sudoku/random': typeof TanstackSudokuSudokuRandomIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tanstack-sudoku/sudoku': typeof TanstackSudokuSudokuIndexRoute
  '/tanstack-sudoku/sudoku/$sudokuId/$sudokuProgress': typeof TanstackSudokuSudokuSudokuIdSudokuProgressRoute
  '/tanstack-sudoku/sudoku/random/$difficulty': typeof TanstackSudokuSudokuRandomDifficultyRoute
  '/tanstack-sudoku/sudoku/$sudokuId': typeof TanstackSudokuSudokuSudokuIdIndexRoute
  '/tanstack-sudoku/sudoku/random': typeof TanstackSudokuSudokuRandomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tanstack-sudoku/sudoku': typeof TanstackSudokuSudokuRouteRouteWithChildren
  '/tanstack-sudoku/sudoku/': typeof TanstackSudokuSudokuIndexRoute
  '/tanstack-sudoku/sudoku/$sudokuId/$sudokuProgress': typeof TanstackSudokuSudokuSudokuIdSudokuProgressRoute
  '/tanstack-sudoku/sudoku/random/$difficulty': typeof TanstackSudokuSudokuRandomDifficultyRoute
  '/tanstack-sudoku/sudoku/$sudokuId/': typeof TanstackSudokuSudokuSudokuIdIndexRoute
  '/tanstack-sudoku/sudoku/random/': typeof TanstackSudokuSudokuRandomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tanstack-sudoku/sudoku'
    | '/tanstack-sudoku/sudoku/'
    | '/tanstack-sudoku/sudoku/$sudokuId/$sudokuProgress'
    | '/tanstack-sudoku/sudoku/random/$difficulty'
    | '/tanstack-sudoku/sudoku/$sudokuId'
    | '/tanstack-sudoku/sudoku/random'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tanstack-sudoku/sudoku'
    | '/tanstack-sudoku/sudoku/$sudokuId/$sudokuProgress'
    | '/tanstack-sudoku/sudoku/random/$difficulty'
    | '/tanstack-sudoku/sudoku/$sudokuId'
    | '/tanstack-sudoku/sudoku/random'
  id:
    | '__root__'
    | '/'
    | '/tanstack-sudoku/sudoku'
    | '/tanstack-sudoku/sudoku/'
    | '/tanstack-sudoku/sudoku/$sudokuId/$sudokuProgress'
    | '/tanstack-sudoku/sudoku/random/$difficulty'
    | '/tanstack-sudoku/sudoku/$sudokuId/'
    | '/tanstack-sudoku/sudoku/random/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TanstackSudokuSudokuRouteRoute: typeof TanstackSudokuSudokuRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tanstack-sudoku/sudoku': {
      id: '/tanstack-sudoku/sudoku'
      path: '/tanstack-sudoku/sudoku'
      fullPath: '/tanstack-sudoku/sudoku'
      preLoaderRoute: typeof TanstackSudokuSudokuRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tanstack-sudoku/sudoku/': {
      id: '/tanstack-sudoku/sudoku/'
      path: '/'
      fullPath: '/tanstack-sudoku/sudoku/'
      preLoaderRoute: typeof TanstackSudokuSudokuIndexRouteImport
      parentRoute: typeof TanstackSudokuSudokuRouteRoute
    }
    '/tanstack-sudoku/sudoku/random/': {
      id: '/tanstack-sudoku/sudoku/random/'
      path: '/random'
      fullPath: '/tanstack-sudoku/sudoku/random'
      preLoaderRoute: typeof TanstackSudokuSudokuRandomIndexRouteImport
      parentRoute: typeof TanstackSudokuSudokuRouteRoute
    }
    '/tanstack-sudoku/sudoku/$sudokuId/': {
      id: '/tanstack-sudoku/sudoku/$sudokuId/'
      path: '/$sudokuId'
      fullPath: '/tanstack-sudoku/sudoku/$sudokuId'
      preLoaderRoute: typeof TanstackSudokuSudokuSudokuIdIndexRouteImport
      parentRoute: typeof TanstackSudokuSudokuRouteRoute
    }
    '/tanstack-sudoku/sudoku/random/$difficulty': {
      id: '/tanstack-sudoku/sudoku/random/$difficulty'
      path: '/random/$difficulty'
      fullPath: '/tanstack-sudoku/sudoku/random/$difficulty'
      preLoaderRoute: typeof TanstackSudokuSudokuRandomDifficultyRouteImport
      parentRoute: typeof TanstackSudokuSudokuRouteRoute
    }
    '/tanstack-sudoku/sudoku/$sudokuId/$sudokuProgress': {
      id: '/tanstack-sudoku/sudoku/$sudokuId/$sudokuProgress'
      path: '/$sudokuId/$sudokuProgress'
      fullPath: '/tanstack-sudoku/sudoku/$sudokuId/$sudokuProgress'
      preLoaderRoute: typeof TanstackSudokuSudokuSudokuIdSudokuProgressRouteImport
      parentRoute: typeof TanstackSudokuSudokuRouteRoute
    }
  }
}

interface TanstackSudokuSudokuRouteRouteChildren {
  TanstackSudokuSudokuIndexRoute: typeof TanstackSudokuSudokuIndexRoute
  TanstackSudokuSudokuSudokuIdSudokuProgressRoute: typeof TanstackSudokuSudokuSudokuIdSudokuProgressRoute
  TanstackSudokuSudokuRandomDifficultyRoute: typeof TanstackSudokuSudokuRandomDifficultyRoute
  TanstackSudokuSudokuSudokuIdIndexRoute: typeof TanstackSudokuSudokuSudokuIdIndexRoute
  TanstackSudokuSudokuRandomIndexRoute: typeof TanstackSudokuSudokuRandomIndexRoute
}

const TanstackSudokuSudokuRouteRouteChildren: TanstackSudokuSudokuRouteRouteChildren =
  {
    TanstackSudokuSudokuIndexRoute: TanstackSudokuSudokuIndexRoute,
    TanstackSudokuSudokuSudokuIdSudokuProgressRoute:
      TanstackSudokuSudokuSudokuIdSudokuProgressRoute,
    TanstackSudokuSudokuRandomDifficultyRoute:
      TanstackSudokuSudokuRandomDifficultyRoute,
    TanstackSudokuSudokuSudokuIdIndexRoute:
      TanstackSudokuSudokuSudokuIdIndexRoute,
    TanstackSudokuSudokuRandomIndexRoute: TanstackSudokuSudokuRandomIndexRoute,
  }

const TanstackSudokuSudokuRouteRouteWithChildren =
  TanstackSudokuSudokuRouteRoute._addFileChildren(
    TanstackSudokuSudokuRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TanstackSudokuSudokuRouteRoute: TanstackSudokuSudokuRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
